/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_myntlabs_pgn_core_BRCoreJniReference */

#ifndef _Included_org_myntlabs_pgn_core_BRCoreJniReference
#define _Included_org_myntlabs_pgn_core_BRCoreJniReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_myntlabs_pgn_core_BRCoreJniReference
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_myntlabs_pgn_core_BRCoreJniReference_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
